Feat/server parsing (Reopen!)
404-DriverNotFound/200-OK pull request #22
Opened 2021-04-29 08:04 UTC by exgs

## **WHAT?**
webserv.config 파일 파싱해서 클래스에 저장하도록 하는 부분 구현함.

## **WHY?**
webserv 프로그램을 만드는데 시작점이라서, 빠르게 작성할 필요가 있음. 일딴은 가볍지만 향후에 영향을 안 끼치는 정도로 구현해서 연결하면 좋을 것 같음.

## **TESTING**
1. srcs/ServerParsing 에서 makefile 을 실행시켜서 실행 파일을 만든다.

2. ```c++
   int SetServer(Server &servers, std::vector<std::string> &gnl)`
   ```

   해당함수가 파싱을 진행한다.

3. ./a.out 으로 출력하여, webserv.config와 값을 비교한다.

## ISSUE and REFERENCE
Resolve: #4 #5 #6
https://www.notion.so/nginx-4aa332c284a74f7481c7458472a42a9e

2021-04-29 08:58 UTC, PennyBlack2008 commented
srcs/ServerParsing 에서 Make 잘 되고 실제 nginx config 는 잘 모르지만, conf 파일과 출력 결과물이 합리적이어서 활용할 수 있을 것같다.
추가한 yunslee_test 폴더에서는 yunslee 의 코드에 우리가 의문이 생길 때마다 공부하면 좋은 예제 코드가 있어서 괜찮은듯

2021-04-29 14:06 UTC, kohyounghwan requested changes
동작확인했는데 코드리뷰 테스트용으로 몇개 남겨봤음

2021-04-29 14:06 UTC, kohyounghwan commented on base_headers/Config.hpp
> +	Config &operator=(const Config &);
```suggestion
	Config&	operator=(const Config &);
```
코드 리뷰 테스트용으로 몇개 남겨봄!

2021-04-29 14:06 UTC, kohyounghwan commented on base_headers/Path.hpp
> +	Path(std::string const &);
```suggestion
	Path(std::string const&);
```

2021-04-29 14:06 UTC, kohyounghwan commented on base_headers/Path.hpp
> +	Path(Path const &);
```suggestion
	Path(Path const&);
```

2021-04-29 14:06 UTC, kohyounghwan commented on base_headers/Webserver.hpp
> +
```suggestion
```

2021-04-30 09:02 UTC, kohyounghwan approved these changes
굿

2021-04-30 09:04 UTC, merged